<?php
echo '<!DOCTYPE HTML>';
echo '<html>';
echo '<body>';
echo '<div class="footer">';
echo '<div class="container">';
echo '<div class="col-md-3 grid_3">';
echo '<h4>Navigate</h4>';
echo '<ul class="f_list f_list1">';
echo '<li><a href="index.html">Home</a></li>';
echo '<li><a href="login.html">Sign In</a></li>';
echo '<li><a href="login.html">Join Now</a></li>';
echo '<li><a href="about.html">About</a></li>';
echo '</ul>';
echo '<ul class="f_list">';
echo '<li><a href="features.html">Features</a></li>';
echo '<li><a href="terms.html">Terms of use</a></li>';
echo '<li><a href="contact.html">Contact Us</a></li>';
echo '<li><a href="jobs.html">Post a Job</a></li>';
echo '</ul>';
echo '<div class="clearfix"> </div>';
echo '</div>';
echo '<div class="col-md-3 grid_3">';
// echo '<h4>Twitter Widget</h4>';
// echo '<div class="footer-list">';
// echo '<ul>';
// echo '<li><i class="fa fa-twitter tw1"> </i><p><span class="yellow"><a href="#">consectetuer</a></span> adipiscing elit web design</p></li>';
// echo '<li><i class="fa fa-twitter tw1"> </i><p><span class="yellow"><a href="#">consectetuer</a></span> adipiscing elit web design</p></li>';
// echo '<li><i class="fa fa-twitter tw1"> </i><p><span class="yellow"><a href="#">consectetuer</a></span> adipiscing elit web design</p></li>';
// echo '</ul>';
// echo '</div>';
echo '</div>';
echo '<div class="col-md-3 grid_3">';

echo '</div>';
echo '<div class="col-md-3 grid_3">';
echo '<h4>Sign up for our newsletter</h4>';
echo '<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam.</p>';
echo '<form>';
echo '<input type="text" class="form-control" placeholder="Enter your email">';
echo '<button type="button" class="btn red">Subscribe now!</button>';
echo '</form>';
echo '</div>';
echo '<div class="clearfix"> </div>';
echo '</div>';
echo '</div>';
echo '<div class="footer_bottom">';
echo '<div class="container">';
echo '<div class="col-sm-2">';
echo '		<ul class="f_list2">';
echo '<li><a href="jobs.html">Russia Jobs</a></li>';
echo '<li><a href="jobs.html">Australia Jobs</a></li>';
echo '<li><a href="jobs.html">Srilanka Jobs</a></li>';
echo '<li><a href="jobs.html">Poland Jobs</a></li>';
echo '</ul>';
echo '	</div>';
echo '	<div class="col-sm-2">';
echo '		<ul class="f_list2">';
echo '<li><a href="jobs.html">New Zealand Jobs</a></li>';
echo '<li><a href="jobs.html">Pakistan Jobs</a></li>';
echo '<li><a href="jobs.html">Srilanka Jobs</a></li>';
echo '<li><a href="jobs.html">Irland Jobs</a></li>';
echo '</ul>';
echo '	</div>';
echo '	<div class="col-sm-2">';
echo '		<ul class="f_list2">';
echo '<li><a href="jobs.html">Canada Jobs</a></li>';
echo '<li><a href="jobs.html">Germany Jobs</a></li>';
echo '<li><a href="jobs.html">China Jobs</a></li>';
echo '<li><a href="jobs.html">Nepal Jobs</a></li>';
echo '</ul>';
echo '	</div>';
echo '	<div class="clearfix"> </div>';
echo '<div class="copy">';
echo '<p>Copyright © 2015 Seeking . All Rights Reserved . Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>
