<?php
echo '<!DOCTYPE HTML>';
echo '<html>';
echo '<head>';
echo '<title>Seeking an Job Portal Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<meta name="keywords" content="Seeking Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template" />';
echo '<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>';
echo '<link href="css/bootstrap-3.1.1.min.css" rel="stylesheet" type="text/css" />';
echo '<script src="js/jquery.min.js"></script>';
echo '<script src="js/bootstrap.min.js"></script>';
echo '<link href="css/style.css" rel="stylesheet" type="text/css" />';
echo '<link href="css/font-awesome.css" rel="stylesheet">';
echo '</head>';
echo '<body>';
echo '<nav class="navbar navbar-default" role="navigation">';
echo '<div class="container">';
echo '<div class="navbar-header">';
echo '<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">';
echo '<span class="sr-only">Toggle navigation</span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '</button>';
echo '<a class="navbar-brand" href="index.html"><img src="images/logo.png" alt=""/></a>';
echo '</div>';
echo '<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" style="height: 1px;">';
echo '<ul class="nav navbar-nav">';
echo '<li class="dropdown">';
echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown">Jobs<b class="caret"></b></a>';
echo '<ul class="dropdown-menu">';
echo '<li><a href="jobs.html">Job Search</a></li>';
// echo '<li><a href="recruiters.html">Recruiters you are following</a></li>';
// echo '<li><a href="codes.html">Shortcodes</a></li>';
echo '</ul>';
echo '</li>';
echo '<li class="dropdown">';
echo '	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Services<b class="caret"></b></a>';
echo '<ul class="dropdown-menu multi-column columns-3">';
echo '<div class="row">';
echo '<div class="col-sm-4">';
echo '<ul class="multi-column-dropdown">';
echo '<li><a href="services.html">Action</a></li>';
echo '<li><a href="services.html">Another action</a></li>';
echo '<li><a href="services.html">Something else here</a></li>';
echo '<li class="divider"></li>';
echo '<li><a href="services.html">Separated link</a></li>';
echo '<li class="divider"></li>';
echo '<li><a href="services.html">One more separated link</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-sm-4">';
echo '<ul class="multi-column-dropdown">';
echo '<li><a href="services.html">Action</a></li>';
echo '<li><a href="services.html">Another action</a></li>';
echo '<li><a href="services.html">Something else here</a></li>';
echo '<li class="divider"></li>';
echo '<li><a href="services.html">Separated link</a></li>';
echo '<li class="divider"></li>';
echo '<li><a href="services.html">One more separated link</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-sm-4">';
echo '<ul class="multi-column-dropdown">';
echo '<li><a href="services.html">Action</a></li>';
echo '<li><a href="services.html">Another action</a></li>';
echo '<li><a href="services.html">Something else here</a></li>';
echo '<li class="divider"></li>';
echo '<li><a href="services.html">Separated link</a></li>';
echo '<li class="divider"></li>';
echo '<li><a href="services.html">One more separated link</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</ul>';
echo '</li>';
echo '<li class="dropdown">';
echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dashboard<b class="caret"></b></a>';
echo '<ul class="dropdown-menu">';
echo '<li><a href="login.html">Jobs Dashboard</a></li>';
echo '<li><a href="recruiters.html">Recruiters you are following</a></li>';
echo '<li><a href="codes.html">Shortcodes</a></li>';
echo '</ul>';
echo '</li>';
echo '<li class="dropdown">';
echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>';
echo '<ul class="dropdown-menu">';
echo '<li><a href="jobs.html">Walk-ins</a></li>';
echo '<li><a href="jobs.html">Bpo Jobs</a></li>';
echo '<li><a href="jobs.html">Teaching Jobs</a></li>';
echo '<li><a href="jobs.html">Diploma Jobs</a></li>';
echo '<li><a href="jobs.html">Tech Support</a></li>';
echo '<li><a href="jobs.html">Finance Jobs</a></li>';
echo '<li><a href="jobs.html">Part time Jobs</a></li>';
echo '<li><a href="jobs.html">Health Care</a></li>';
echo '<li><a href="jobs.html">Hospitality</a></li>';
echo '<li><a href="jobs.html">Internships</a></li>';
echo '<li><a href="jobs.html">Research Jobs</a></li>';
echo '<li><a href="jobs.html">Defence Jobs</a></li>';
echo '</ul>';
echo '</li>';
echo '<li><a href="login.html">Login</a></li>';
echo '<li><a href="resume.html">Upload Resume</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="clearfix"> </div>';
echo '</div>';
echo '</nav>';
 ?>
